### ISSUE TITLE
Weird line break cause overlapping

### ISSUE THREAD

**Issue by mcwindy** [microsoft/vscode-hexeditor#214]
![image](https://user-images.githubusercontent.com/40684304/108717126-dfaa0c00-7557-11eb-876e-3f0cea0dbd4d.png)

**Comment by lramos15** [comment]
Can you provide more information please like your phone family and size? If you try to zoom the editor currently doesn't scale well.

**Comment by mcwindy** [comment]
"editor.fontFamily": "fira code, Consolas, 'Courier New', monospace",
"editor.fontSize": 14,

I think it was caused by ["fira code"](https://github.com/tonsky/FiraCode).

**Comment by lramos15** [comment]
Thannks for reporting this, I will leave it open for now but it appears to be caused by the larger issue which is the UI in the hex editor isn't very responsive

**Comment by dimitris-triantafyllidis** [comment]
On my Linux system the rendering seems fine with a font size of 13 instead of the default 14. With the default font size, trying a couple of different fonts (defaults and Source Code Pro) and zoom factors (1 and 1.25) did not make any difference.

**Comment by benizl** [comment]
I'm getting this too, IBM Plex Mono, Size 14 (sizes 13 and under are fine). Interesting, perhaps, to note that it doesn't happen if the symbols are selected
![hexedit-render-bug](https://user-images.githubusercontent.com/15090/114816573-c016bd80-9dfb-11eb-8692-fbb386261fcb.png)

**Comment by lramos15** [comment]
I have made the hex editor adapt to font size changes. Please let me know if this helps :)

**Comment by mcwindy** [comment]
![image](https://user-images.githubusercontent.com/40684304/116422046-f16aa100-a871-11eb-9fda-16aed01cb2b3.png)

I think the problem is still unresolved.

**Comment by lramos15** [comment]
Sorry, I was silly and said try it but didn't publish a new version. I have just published v 1.6.0 of the hex editor.

**Comment by mcwindy** [comment]
![image](https://user-images.githubusercontent.com/40684304/116783976-4d2c6880-aac4-11eb-94ce-3c5cabfad1ae.png)

![image](https://user-images.githubusercontent.com/40684304/116783970-43a30080-aac4-11eb-96ff-b9b79de1679f.png)

![image](https://user-images.githubusercontent.com/40684304/116783796-5d901380-aac3-11eb-9e77-2d3914ae9edc.png)

I'm afraid this problem remains unsolved. Do you need more information?

**Comment by nijakow** [comment]
I second this. Hex editor version 1.8.2 on Arch Linux, happens with every monospace font I've tried.
The line breaks always occur after a 0x28 character in my hex file. Maybe that helps ;-)

**Comment by lramos15** [comment]
Thanks @nijakow for the additional information. This issue is still under investigation and hasn't been forgotten, just a lot of work going on in VS Code right now 😄

**Comment by mcwindy** [comment]
I tested Cascadia Mono SemiLight, fira code and Consolas on my computer, this problem no longer exists.

版本: 1.60.0-insider (user setup)
提交: 58454f7bec838f79fe2422ab5914419147d82e40
日期: 2021-08-13T05:15:29.421Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by schuelermine** [comment]
This issue is happening to me when opening a NixOS ISO (truncated) on Linux (NixOS). The font is JetBrains Mono.

**Comment by connor4312** [comment]
I no longer see this since the rework. Let us know if you still run into it.
